#!/bin/sh
function raw2bvp {
  loc=$(dirname "$0")
  cd ..
  current="$(pwd)"
  cd work
  size=$(ls raw/0 | head -1 | grep -oE "[0-9]{1,4},[0-9]{1,4},[0-9]{1,4}")
  for ((i=0; i<60; i++)); do
    node $loc/raw2bvp.js -m 1 -i "raw/${i}/red${size}.raw" -d ${size//\,/x} -f R8 -G false -m 2 -i "raw/$i/green${size}.raw" -d ${size//\,/x} -f R8 -G false -m 3 -i "raw/$i/blue${size}.raw" -d ${size//\,/x} -f R8 -G false -m 4 -i "raw/$i/alpha${size}.raw" -d ${size//\,/x} -f R8 -G false -o "$current/${2:-"bvp"}"/$i.bvp
  done
}
current=$(pwd)
mkdir /dev/shm/work
ln -s /dev/shm/work ./work
cd work
loc=$(dirname "$0")
(time blender -b "$current/${1:-"example_scene.blend"}" -P $loc/blender_scene2vdb.py) &> timeb.txt
(time combiner) &> timec.txt
mkdir -p "$current/${2:-"bvp"}"
size=$(ls raw/0 | head -1 | grep -oE "[0-9]{1,4},[0-9]{1,4},[0-9]{1,4}")
(time raw2bvp "$@") &> timer.txt
cd ..
# rm -rf /dev/shm/work work
echo $size
