#!/bin/sh
loc=$(dirname "$0")
blender -b "${1:-"example_scene.blend"}" -P $loc/blender_scene2vdb.py
combiner
rm -rf vdb
mkdir -p "${2:-"bvp"}"
for ((i=0; i<60; i++)); do
  node $loc/raw2bvp.js -m 1 -i raw/$i/red126,125,123.raw -d 126x125x123 -f R8 -G false -m 2 -i raw/$i/green126,125,123.raw -d 126x125x123 -f R8 -G false -m 3 -i raw/$i/blue126,125,123.raw -d 126x125x123 -f R8 -G false -o "${2:-"bvp"}"/$i.bvp
done
rm -rf raw